version: "3.8"
networks:
  lara_network:
    driver: bridge
services:
  nginx:
    image: nginx:stable-perl
    container_name: "ngnix"
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/logs/nginx:/var/log/nginx
      - ./docker/config/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - lara_network
  mysql:
    image: mysql:8.0.28
    container_name: "mysql"
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: jewels
      MYSQL_ROOT_PASSWORD: 123
    networks:
      - lara_network
  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: "lara_frame"
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/config/docker-php-ram-limit.ini:/usr/local/etc/php/conf.d/docker-php-ram-limit.ini
      - ./docker/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - "9000:9000"
    networks:
      - lara_network
